services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://rem-farms.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
